#theme: jekyll-theme-dinky
remote_theme: just-the-docs/just-the-docs
"pyp on github":
-"https://github.com/thepyedpiper/pyp"
logo: "https://opensource.imageworks.com/images/large/pyp.jpg"
ga_tracking: UA-24927622-3
